name: Build Ink! contract

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup install nightly
          rustup default nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly

      - name: Install cargo-contract
        run: cargo install cargo-contract --version 4.0.0 --locked

      - name: Build contract
        run: cargo contract build --release
